---
title: "hent-ssb-data"
author:
- Kevin Ha - 571821
- Ola Andre Olofsson - 170745
fontsize: 12pt
linestrech: 1.5
output:
  pdf_document: default
  html_document:
    df_print: paged
  word_document: default
lang: no-NB
---

```{r setup, include=FALSE}
suppressPackageStartupMessages({
library(PxWebApiData)
library(tidyverse)
library(lubridate)
})
knitr::opts_chunk$set(echo = FALSE, include = FALSE)
```

```{r knr}
load("~/Dropbox/Master of Science in Business/Semester 1/MSB105 Data Science/Ass4/ass4-h21--OAO-KH/data/knr.Rdata")
```

```{r pm2_raw}
pm2_raw <- ApiData(
  urlToData = "06035",
  Region = knr,
  ContentsCode = "KvPris",
  Boligtype = "01",
  Tid = c(as.character(2002:2017)))

# Skifter navn på variablene Region, Tid og value som angitt i oppgaven
df_pm2_raw <- data.frame(
    knr = pm2_raw[["dataset"]]$Region,
    aar = pm2_raw[["dataset"]]$Tid,
    pm2 = pm2_raw[["dataset"]]$value
    )

#  For å slippe å hanske med det uhåndterlig lange navnet på dette elementet skifter vi først navn på dette til “desc”.
names(pm2_raw)[[1]] <- "desc"
```


```{r knavn}
pm2 <- pm2_raw[[1]] %>%
  mutate(knavn = pm2_raw$desc$region)
```
